# -*- coding: utf-8 -*-
"""HeartDiseaseDNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IvoGt3WeEfFcmX6Es_s8MDeugrfbXxac
"""

import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

path = 'data/Heart_Disease_Prediction.csv'
Db = pd.read_csv(path)
Db.head()

print(Db.isnull().sum())
Db['Heart Disease']=Db['Heart Disease'].map({'Presence':1,'Absence':0})

X = Db.drop('Heart Disease',axis=1)
Y = Db['Heart Disease']
X_train , X_test , Y_train , Y_test = train_test_split(X,Y, test_size=0.2 , random_state = 43)
X_train_ , X_train_val , Y_train_ , Y_train_val = train_test_split(X_train , Y_train,test_size=0.15,random_state=43)
scaler = RobustScaler()
X_train_ = scaler.fit_transform(X_train_)
X_train_val = scaler.transform(X_train_val)
X_test = scaler.transform(X_test)

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(100,activation='leaky_relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(64,activation='leaky_relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(24,activation='leaky_relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(8,activation='leaky_relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0003), loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(X_train_, Y_train_, epochs=20,batch_size=16, validation_data=(X_train_val, Y_train_val))
model.evaluate(X_test, Y_test, verbose=2)

import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'],label='train_accuracy')
plt.plot(history.history['val_accuracy'],label='val_accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)
cm = confusion_matrix(Y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Healthy', 'Sick'],
            yticklabels=['Healthy', 'Sick'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Heart Disease Confusion Matrix')
plt.show()

